### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'parse'

### ISSUE THREAD

**Issue by Germanunkol** [Moguri/blend2bam#87]
I have issues with "urllib" (see error below) that, according to my search on the net, have to do with how urllib is used...?
I don't think urllib is directly used by blend2bam, but by gltf?

I've tried with python versions: 3.11.6, 3.10.13, 3.8.8, all of them printed the error below. For all of them, I did
`python3 -m pip install panda3d-blend2bam`
followed by
`python3 -m blend2bam  --blender-dir $blender_dir $in_file $out_file --textures copy`

I **did** get it to work with python version 3.7.17 though, using the same instructions above.

I'm using Ubuntu 23.10 with an (almost) fresh install and pyenv to configure my python environments.

```
Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-18 23:31:25)
Read prefs: "/home/me/.config/blender/3.6/config/userpref.blend"
Read blend: "/home/me/Projects/WBWB/CreatureGenerator/generator.blend"
Error: Tangent space can only be computed for tris/quads, aborting
21:49:34 | WARNING: Could not calculate tangents. Please try to triangulate the mesh first.
Error: Tangent space can only be computed for tris/quads, aborting
21:49:34 | WARNING: Could not calculate tangents. Please try to triangulate the mesh first.


Blender quit
Traceback (most recent call last):
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/blend2bam/cli.py", line 60, in convert
    outfiles = tmp2dst.convert(tmpdir, dstdir, tmpfiles)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/blend2bam/gltf2bam.py", line 74, in convert
    run_gltf2bam(src, dst, self.cli_args)
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/blend2bam/gltf2bam.py", line 26, in run_gltf2bam
    runpy.run_module('gltf.cli', run_name='__main__', alter_sys=True)
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/gltf/cli.py", line 159, in <module>
    main()
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/gltf/cli.py", line 123, in main
    converter.update(gltf_data)
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/gltf/_converter.py", line 178, in update
    self.load_texture(texid, gltf_tex, gltf_data)
  File "/home/me/.pyenv/versions/3.11.6/lib/python3.11/site-packages/gltf/_converter.py", line 565, in load_texture
    uri = urllib.parse.unquote(uri)
          ^^^^^^^^^^^^
AttributeError: module 'urllib' has no attribute 'parse'

Failed to convert all files
```
