### ISSUE TITLE
Crash after updating blender to 4.2

### ISSUE THREAD

**Issue by someoneetc** [Moguri/blend2bam#94]
Seemingly due to a change in some interface, this import

`from io_scene_gltf2.io.com.gltf2_io_debug import set_output_level #pylint: disable=import-error
 set_output_level('WARNING')`

causes the program to crash

`ImportError: cannot import name 'set_output_level' from 'io_scene_gltf2.io.com.gltf2_io_debug' (/usr/share/blender/4.2/scripts/addons_core/io_scene_gltf2/io/com/gltf2_io_debug.py)`.

Removing those two lines fixes the problem though.
